name: who am i?

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  checkout:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Check Responses (v3)
        run: |
          gh api https://api.github.com/user ||
          true

      - name: Check Viewer (GraphQL)
        run: |
          gh api graphql -f query=" \
           { \
             \"query\": \"query { viewer { login }}\" \
           } \
          " ||
          true
