name: who am i?

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  checkout:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Check Responses (v3)
        run: |
          gh api https://api.github.com/app ||
          true

      - name: Check Viewer (GraphQL)
        run: |
          gh api graphql -f query='query { viewer { login }}" ||
          true
